complex-numbers: fix tests (#157)
The current tests failed with:

/2: Unknown procedure: plunit_conjugate:conjugate/2
  However, there are definitions for:
        conjugate/2
ERROR: /Users/erik/Code/exercism/solutions/prolog/complex-numbers/complex_numbers_tests.plt:122:
        test conjugate_a_number_with_real_and_imaginary_part: received error: plunit_conjugate:'unit body'/2: Unknown procedure: plunit_conjugate:conjugate/2
  However, there are definitions for:
        conjugate/2

This was due to the name of the tests begin/end (`conjugate`) matching the term that was tested (`conjugate`).